name: First Workflow

on: push 

jobs: 
  build: 
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [16.x]

    steps: 
     -uses: actions/checkout@v2 
     -name: Use node js
      uses: actions/setup-node@v1
     -name: Install dependencies
      run: npm ci     